/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosRouteImport } from './routes/pos'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TChar123tableNumberChar125RouteImport } from './routes/t.{$tableNumber}'

const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TChar123tableNumberChar125Route =
  TChar123tableNumberChar125RouteImport.update({
    id: '/t/{$tableNumber}',
    path: '/t/{$tableNumber}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/board': typeof BoardRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/pos': typeof PosRoute
  '/t/{$tableNumber}': typeof TChar123tableNumberChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/board': typeof BoardRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/pos': typeof PosRoute
  '/t/{$tableNumber}': typeof TChar123tableNumberChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/board': typeof BoardRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/pos': typeof PosRoute
  '/t/{$tableNumber}': typeof TChar123tableNumberChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/board'
    | '/kitchen'
    | '/menu'
    | '/pos'
    | '/t/{$tableNumber}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/board'
    | '/kitchen'
    | '/menu'
    | '/pos'
    | '/t/{$tableNumber}'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/board'
    | '/kitchen'
    | '/menu'
    | '/pos'
    | '/t/{$tableNumber}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BoardRoute: typeof BoardRoute
  KitchenRoute: typeof KitchenRoute
  MenuRoute: typeof MenuRoute
  PosRoute: typeof PosRoute
  TChar123tableNumberChar125Route: typeof TChar123tableNumberChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/{$tableNumber}': {
      id: '/t/{$tableNumber}'
      path: '/t/{$tableNumber}'
      fullPath: '/t/{$tableNumber}'
      preLoaderRoute: typeof TChar123tableNumberChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BoardRoute: BoardRoute,
  KitchenRoute: KitchenRoute,
  MenuRoute: MenuRoute,
  PosRoute: PosRoute,
  TChar123tableNumberChar125Route: TChar123tableNumberChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
